.SH David Wickes
.PP
An agile, iterative, and test-driven developer.
.SS Saltpay (https://www.saltpay.co/)
.SS \f[I]Senior Developer / Tech Lead (May 2022 - Present)\f[R]
.IP \[bu] 2
Provider of payments services to small and medium enterprises
.IP \[bu] 2
Responsible for the integration of dependencies for the onboarding of
customers
.IP \[bu] 2
Consulted internally on testing strategies and TDD
.IP \[bu] 2
Built tooling within the team to improve process
.SS Skills
.IP \[bu] 2
Go programming language
.IP \[bu] 2
Architecture and decision documentation
.IP \[bu] 2
Deployment on a Kubernates cluster
.SS Triptease (https://www.triptease.com/)
.SS \f[I]Senior Developer (July 2021 - April 2022)\f[R]
.IP \[bu] 2
Hotel digital services company manging digital advertising
.IP \[bu] 2
Worked in team responsible for display advertising
.SS Skills
.IP \[bu] 2
Primarily programmed in TypeScript
.IP \[bu] 2
Management of a statistical model to calculate the correct advertising
bids
.IP \[bu] 2
Contributed multiple learning sessions to help teams learn TypeScript
.SS Acuris (http://www.acuris.com/)
.SS \f[I]Senior Developer (July 2019 - June 2021)\f[R]
.IP \[bu] 2
Financial journalism company, providing alerting and research services
to multiple sectors.
.IP \[bu] 2
Worked initially on the platform team building tooling around AWS
.IP \[bu] 2
Moved to a product team building web applications
.IP \[bu] 2
Initiated and ran the departments associate developer mentoring
programme
.SS Skills
.IP \[bu] 2
Use of graphical JavaScript libraries to display information
.IP \[bu] 2
Event sourced (https://martinfowler.com/eaaDev/EventSourcing.html)
backend architecture in TypeScript
.IP \[bu] 2
Rapid prototyping using spreadsheets as backend (both Excel and Google
Sheets)
.IP \[bu] 2
Next.js (https://nextjs.org/), a React based web framework
.IP \[bu] 2
Promoted the use of DevOps and Agile techniques for building software
.IP \[bu] 2
Configuring multiple AWS services using
Terraform (https://www.terraform.io/)
.IP \[bu] 2
Working with Svelte (https://svelte.dev/)
.SS SpringerNature Digital (http://www.springernature.com)
.SS \f[I]Developer (October 2017 - July 2019)\f[R]
.IP \[bu] 2
International scientific publisher
.IP \[bu] 2
Joined to work as part of a small innovations team, working across the
company
.IP \[bu] 2
Dissolution of team resulted in move to high-priority payments project
.IP \[bu] 2
Led a weekly lunch club learning Lisp(s)
.SS Skills
.IP \[bu] 2
Small applications as experiments to gather the maximum information on
real requirements
.IP \[bu] 2
Continuous delivery (https://continuousdelivery.com/) with trunk based
development (https://trunkbaseddevelopment.com/)
.IP \[bu] 2
Leveraging modern HTML and CSS to build simple, functional web
applications
.IP \[bu] 2
Building browser extensions as an integration point across legacy
systems
.IP \[bu] 2
An event sourced architecture built on top of
Kotlin (https://kotlinlang.org/) and PostgreSQL
.IP \[bu] 2
Deploying applications on a Cloud
Foundry (https://www.cloudfoundry.org/) platform
.SS Acuris (http://www.acuris.com/)
.SS \f[I]Developer (January 2015 - October 2017), Lead Developer (May 2016 - September 2016)\f[R]
.IP \[bu] 2
Built a web-scraping and alerting system for US bankruptcy courts using
a microservice architecture.
.IP \[bu] 2
Contributed to creation of new content delivery pipelines for the core
business
.IP \[bu] 2
Led a team until I asked to be allowed to focus on development
.IP \[bu] 2
Led and iterated on the structure for regular hackdays
.SS Skills
.IP \[bu] 2
Extending and upgrading NodeJS apps to use ES2015 features
.IP \[bu] 2
Languages - Groovy, Go, JavaScript, TypeScript
.IP \[bu] 2
Building frontends in vanilla JS, React and Redux
.IP \[bu] 2
Participated and led in learning and adoption of Go across development
teams
.IP \[bu] 2
Building RESTful services using Express, Spark, Ratpack
.IP \[bu] 2
Using RabbitMQ to connect services
.IP \[bu] 2
Monitoring and logging using Graphite, DataDog, Logstash and Logentries
.IP \[bu] 2
Databases - MSSQL, Elasticsearch, MongoDB
.IP \[bu] 2
Web scraping using various libraries and regular expressions
.IP \[bu] 2
Participating in and leading retrospectives
.SS Makers Academy (http://www.makersacademy.com/)
.SS \f[I]Student (August 2014 - October 2014), Tutor (October 2014 - December 2014)\f[R]
.IP \[bu] 2
Full-stack web development bootcamp in Ruby, JavaScript, Rails, Sinatra
and NodeJS
.IP \[bu] 2
Learned TDD/BDD, pair programming and other modern development practices
.SS Skills
.IP \[bu] 2
Ruby and JavaScript
.IP \[bu] 2
Frontend skills in HTML5, CSS and JQuery
.IP \[bu] 2
Version control with git and GitHub
.SS \f[I]Courses, Conferences, External Activities\f[R]
.IP \[bu] 2
Contributor to Go Time podcast on TDD (https://changelog.com/gotime/185)
and htmx (https://changelog.com/gotime/266)
.IP \[bu] 2
Recent conferences: GopherCon London, Software Craftmanship London,
GopherCon Europe, QCon
.IP \[bu] 2
Lead Developer Workshop: \f[I]Be a brilliant people developer\f[R]
.IP \[bu] 2
\f[I]Single Page Applications with AngularJS and TypeScript\f[R] -
Skills Matter
.IP \[bu] 2
\f[I]Algorithmic
Toolbox\f[R] (https://www.coursera.org/account/accomplishments/records/C58NGM7GQS84)
by University of California, San Diego & Higher School of Economics on
Coursera
.SS Languages
.IP \[bu] 2
Used in production: Kotlin, JavaScript/TypeScript, Groovy, Ruby, Go
.IP \[bu] 2
Used outside of work: Common Lisp, Scheme, Racket, OCaml, Smalltalk
.SS \f[I]Other Employment\f[R]
.SS Liberis
.PP
\f[I]Marketing Executive (March 2014 - August 2014)\f[R]
.SS Polyglobe Group
.PP
\f[I]Marketing Executive (March 2013 - February 2014)\f[R]
.SS Education
.PP
.TS
tab(@);
l l l.
T{
Dates
T}@T{
Institution
T}@T{
Subject(s)
T}
_
T{
2003 - 2005
T}@T{
University of Warwick
T}@T{
MA Continental Philosophy
T}
T{
2000 - 2003
T}@T{
University of Warwick
T}@T{
BA Philosophy (1:1)
T}
T{
1991 - 1998
T}@T{
Wisbech Grammar School
T}@T{
A level Maths, Biology & Chemistry; 10 GCSEs
T}
.TE
.SS I Like
.PP
TDD, DDD, functional programming,
chess (https://www.chess.com/member/gypsydave5), boardgames, playing the
recorder, early music, Oxford commas, and the philosophy of language.
.SS Contact
.PP
You can reach me as \[at]gypsydave5 (https://twitter.com/gypsydave5) on
Twitter and dave.wickes\[at]gmail.com (mailto:dave@gypsydave5.com) by
email.
There\[aq]s a blog (blog.gypsydave5.com (http://blog.gypsydave5.com/)),
and my GitHub (https://github.com/gypsydave5) account too if you\[aq]d
like to see what I\[aq]m up to and thinking.
